### ISSUE TITLE
Image_inspect_content - Initial view and switching

### ISSUE THREAD

**Issue by carzooma** [jefferythewind/b#21]
When an image is selected in view_sighting, that image should be expanded view image on Image_inspect_content. 

Then when in image_inspect_content when someone pics an alternative image in the row below it should switch out.

**Comment by jefferythewind** [comment]
@carzooma how we doing on this one, I think this is done, no?  Didn't we decided just to have the full page image?  Or did we also want to be able to swipe/click to see previous/next?

**Comment by carzooma** [comment]
No i believe what we have is working well from the user perspective.
