### ISSUE TITLE
Sign Up Register Page 

### ISSUE THREAD

**Issue by jefferythewind** [jefferythewind/b#26]
At least google and FB auto register, like this:
<img width="567" alt="screen shot 2016-09-21 at 16 07 15" src="https://cloud.githubusercontent.com/assets/18137743/18714293/9a8ba8d6-8015-11e6-887c-40cf9b735c6f.png">

**Comment by carzooma** [comment]
@jefferythewind can you send me the link of where you found this? Would be really helpfu

**Comment by carzooma** [comment]
@jefferythewind I am not sure where this should go so i am building the template/form in the login.html page under registration.  Maybe it should be signup.html?

**Comment by jefferythewind** [comment]
@carzooma yes I think this should go in the signup.html file, but i don't think that file is shown yet on the site.  That screen shot is from addthis.com

**Comment by jefferythewind** [comment]
https://developers.google.com/identity/

**Comment by jefferythewind** [comment]
looks like google has a service that can allow users to authenticate using all the main social apps
https://firebase.google.com/docs/auth/

**Comment by carzooma** [comment]
+1 for using firebase solution
