### ISSUE TITLE
Sign In to Comment

### ISSUE THREAD

**Issue by carzooma** [jefferythewind/b#28]
When I look at a sighting when not signed in, I should be notified, sign in to comment and like the sighting. 

It should be something like a snack bar, https://getmdl.io/components/index.html#snackbar-section

**Comment by jefferythewind** [comment]
@carzooma I think this snack bar item could be used for all pages when not logged in, not just the sighting page

**Comment by jefferythewind** [comment]
That way we could just add this piece to the base.html file
