### ISSUE TITLE
Maximize image to full screen when clicked on View Sighting page

### ISSUE THREAD

**Issue by jefferythewind** [jefferythewind/b#3]

**Comment by carzooma** [comment]
Please create a blank page which will be created and draws all the images into, similar to what i made before.  I need piece of slate to work from so i can style things properly

**Comment by jefferythewind** [comment]
@carzooma you will see the I built this into the view_sighting page.  Find the div with id="image_inspect" at bottom of HTML section.  click on the photos to try it out.

press ESC to close.  If you want to add a button to close it we can do that as well, you can get everything looking they way you want, and I will help you attach the close functionality.

**Comment by jefferythewind** [comment]
@carzooma I fixed the responsive popup problem, but the big picture is loading way too big.  Looks like the small pic is the right size.

**Comment by jefferythewind** [comment]
This was put in, and continued in another issue.
