### ISSUE TITLE
User contributed content documentation

### ISSUE THREAD

**Issue by jefferythewind** [jefferythewind/b#52]
User contributed content, except username info, should be considered public content.  This includes all information pertaining to sightings, feedback, comments and other info. You're not required to enter personally identifiable information into the Birding book website. All personally identifiable information is stored on the Google firebase servers.

**Comment by carzooma** [comment]
User contributed content, except username info, should be considered public content. This includes all information pertaining to sightings, feedback, comments, avatar and other info. You're not required to enter personally identifiable information into The Birding Book website. 

All personally identifiable information is stored on the Google firebase servers.

**Comment by carzooma** [comment]
Sorry just did a little correction here and there.  This is a User agreement issue and should be placed as a within the Terms of Service
